# https://docs.docker.com/compose/compose-file
version: '3'

networks:
  shared-network:
    driver: bridge

services:

  # This is the core service API.
  travel-api:
    container_name: travel-api
    networks:
      - shared-network
    image: travel-api-amd64:1.0
    ports:
      - 3000:3000 # API
      - 4000:4000 # DEBUG API
    # environment:
      # - GODEBUG=gctrace=1

  # Database
  dgraph:
    container_name: dgraph
    networks:
      - shared-network
    image: dgraph/standalone:v20.03.0
    ports:
      - 8000:8000
      - 8080:8080
      - 9080:9080

