version: '3.8'

services:

  dgraph-zero:
    environment:
      - DGRAPH_ZERO_MY=dgraph-zero:5080

  dgraph-alpha:
    environment:
      - DGRAPH_ALPHA_MY=dgraph-alpha:7080
      - DGRAPH_ALPHA_LRU_MB=1024
      - DGRAPH_ALPHA_ZERO=dgraph-zero:5080
      - DGRAPH_ALPHA_SECURITY=whitelist=0.0.0.0/0
