version: '3.8'

services:

  travel-api:
    environment:
      - TRAVEL_API_KEYS_MAPS_KEY=
      - TRAVEL_DGRAPH_URL=
      - TRAVEL_DGRAPH_AUTH_HEADER_NAME=X-Auth-Token
      - TRAVEL_DGRAPH_AUTH_TOKEN=

  travel-ui:
    environment:
      - TRAVEL_API_KEYS_MAPS_KEY=
      - TRAVEL_DGRAPH_URL=
      - TRAVEL_DGRAPH_AUTH_HEADER_NAME=X-Auth-Token
      - TRAVEL_DGRAPH_AUTH_TOKEN=
      - TRAVEL_DGRAPH_BROWSER_URL=
